version: '3.8'
services:
  zookeeper: 
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "22181:2181"
  broker:
    image: confluentinc/cp-kafka:7.5.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTNER_SECURITY_PROTOCOL_MAP=PALINTEXT:PALINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PALINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    